In [1]:
import pandas as pd 

full_df = pd.read_csv('fma_metadata/tracks.csv', header=[0,1], index_col=0)

small_index = full_df[('set', 'subset')] == 'small'

features_df = pd.read_csv('fma_metadata/features.csv', header=[0,1,2], index_col=0).loc[small_index]

drop_columns = [96,97,98,99,100,101,102,103,104,105,106,107,180,181,182,183,184,185,186,187,188,189,190,191]

# Assign the result of drop() back to small_df
small_df = features_df.drop(columns=features_df.columns[drop_columns])
features_df.head()

feature    chroma_cens                                                    \
statistics    kurtosis
number              01        02        03        04        05        06
track_id
2             7.180653  5.230309  0.249321  1.347620  1.482478  0.531371
5             0.527563 -0.077654 -0.279610  0.685883  1.937570  0.880839
10            3.702245 -0.291193  2.196742 -0.234449  1.367364  0.998411
140           0.533579 -0.623885 -1.086205 -1.081079 -0.765151 -0.072282
141           0.172898 -0.284804 -1.169662 -1.062855 -0.706868 -0.708281

feature                                             ...   tonnetz            \
statistics                                          ...       std
number            07        08        09        10  ...        04        05
track_id                                            ...
2           1.481593  2.691455  0.866868  1.341231  ...  0.054125  0.012226
5          -0.923192 -0.927232  0.666617  1.038546  ...  0.040730  0.012691
10          1.770694  1.604566  0.521217  1.982386  ...  0.074358  0.017952
140        -0.882913 -0.582376 -0.884749 -0.645214  ...  0.157683  0.028070
141        -0.204884  0.023624 -0.642770 -0.786291  ...  0.145994  0.024342

feature                     zcr                                          \
statistics             kurtosis       max      mean    median       min
number            06         01        01        01        01        01
track_id
2           0.012111   5.758890  0.459473  0.085629  0.071289  0.000000
5           0.014759   6.808415  0.375000  0.053114  0.041504  0.000000
10          0.013921  21.434212  0.452148  0.077515  0.071777  0.000000
140         0.025946  11.052547  0.379395  0.052379  0.036621  0.001953
141         0.032111  32.994659  0.415527  0.040267  0.034668  0.002930

feature
statistics      skew       std
number            01        01
track_id
2           2.089872  0.061448
5           2.193303  0.044861
10          3.542325  0.040800
140         3.143968  0.057712
141         4.204097  0.028665

[5 rows x 518 columns]